spring:
    application.name: hello-spring
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: SPRING_BOOT
        password: 1234
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    servlet:
        #파일 업로드 설정
        multipart:
            #1024byte -> 1kb ->1024kb -> 1mb
            #최대업로드 파일크기 설정(100MB: 1024 * 1024 * 100)
            max-file-size: 104857600
            #요청당 최대 업로드 파일크기 설정(10MB: 1024 * 1024 * 10)
            max-request-size: 10485760

# classpath: ==> java, xml 이런 파일을 가지고있는 프로젝트 정보들이 컴파일되어 보관하는 경로
# C:\dev_program\sts_workspace\hello-spring\target\classes : classpath
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:com/hello/forum/**/dao/mapper/*Mapper.xml
    
    
#사용자 설정
app:
   multipart:
   #파일업로드 위치지정
       base-dir: c:/uploadFiles
       #난독화 여부 설정
       obfuscation:
           #파일명 난독화 할 경우 true
           enable: true
           #파일 확장자 가리기 여부 설정
           hide-ext:
               #파일 확장자 가릴경우 true
               enable: true
       available-file-list:
           handler: tika
           enable: true
           list:
               audio/aac,
               video/x-msvideo,
               text/css,
               text/csv,
               application/msword,
               image/gif,
               text/html,
               image/jpeg,
               application/json,
               audio/midi,
               application/x-tika-ooxml
